In [1]:
import pandas as pd
import numpy as np

In [3]:
reviews = pd.read_json("review-North_Dakota.json",lines=True)

In [6]:
reviews.shape

(1109558, 8)

In [7]:
reviews.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.088493e+20,أحمد آل إبراهيم,1600517759614,5.0,I want to join Catholic Christ.,None,None,0x52d94fbefa0e6353:0xf709e2d8674fe3a
1,1.137480e+20,John OpenMinded,1594757122443,5.0,Its Catholic and devout. What more do you need?,None,None,0x52d94fbefa0e6353:0xf709e2d8674fe3a
2,1.089884e+20,Juergen Wolf,1574580027389,5.0,This was my Church in Karlsruhe. However in Ka...,None,None,0x52d94fbefa0e6353:0xf709e2d8674fe3a
3,1.094611e+20,Jamie Lee,1572608951549,4.0,Go with god,None,None,0x52d94fbefa0e6353:0xf709e2d8674fe3a
4,1.177488e+20,lucas03,1604339936721,5.0,(Translated by Google) everything faker not th...,None,None,0x52d94fbefa0e6353:0xf709e2d8674fe3a

In [20]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.],
                   'ABC': ['aa','bb','cc','dd']})

In [21]:
df

   Animal  Max Speed ABC
0  Falcon      380.0  aa
1  Falcon      370.0  bb
2  Parrot       24.0  cc
3  Parrot       26.0  dd

In [22]:
grouped_df = df.groupby('Animal')['Max Speed'].agg(list).reset_index()
grouped_df

   Animal       Max Speed
0  Falcon  [380.0, 370.0]
1  Parrot    [24.0, 26.0]

In [24]:
check = reviews.groupby('gmap_id').agg({'user_id': list, 'name': list, 'time': list, 'rating': list, 'text': list}).reset_index()

In [26]:
check.shape

(11937, 6)

In [32]:
reviews['gmap_id'].nunique()

11937

In [35]:
#check.to_csv('groupby_gmapid.csv')

In [36]:
metadata = pd.read_json('meta-North_Dakota.json', lines=True)

In [39]:
print("Shape of metadata is", metadata.shape)
print(metadata.columns)

Shape of metadata is (11987, 15)
Index(['name', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url'],
      dtype='object')

In [40]:
metadata.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,St Peter & Paul Church,"St Peter & Paul Church, 500 Main St, Karlsruhe...",0x52d94fbefa0e6353:0xf709e2d8674fe3a,None,48.093248,-100.618664,[Catholic church],4.9,7,None,None,{'Accessibility': ['Wheelchair accessible entr...,None,"[0x52d9384b75abac93:0x13526f8266cae6cf, 0x52d9...",https://www.google.com/maps/place//data=!4m2!3...
1,Northwest Martial Arts Academy,"Northwest Martial Arts Academy, 1430 Main Ave,...",0x52c8cbe775edec7d:0xb46e15ed33643070,None,46.875093,-96.802717,[Martial arts school],5.0,8,None,"[[Thursday, 7:30AM–8PM], [Friday, 7:30AM–8PM],...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 7:30AM,"[0x52c8ccbcb1785327:0x2d50311eabd7afc, 0x52cf3...",https://www.google.com/maps/place//data=!4m2!3...
2,Thad's Amazing Magic - Fargo Birthday Party Magic,Thad's Amazing Magic - Fargo Birthday Party Ma...,0x52c8cd270f50bbbb:0x4ee4629598a8090e,None,46.812415,-96.856729,"[Magician, Children's party service]",5.0,58,None,"[[Thursday, Open 24 hours], [Friday, Open 24 h...",{'Amenities': ['Good for kids']},Open 24 hours,"[0x52c8c9613725e9ef:0xc628b86d8593e7e6, 0x52c8...",https://www.google.com/maps/place//data=!4m2!3...
3,Threefold,"Threefold, 212 W Main Ave, Bismarck, ND 58501",0x52d7836b7314da5d:0xc3cc63667b8c13a0,None,46.805707,-100.792990,"[Film production company, Video editing servic...",5.0,5,None,"[[Wednesday, 9AM–6PM], [Thursday, 9AM–6PM], [F...",None,Closed ⋅ Opens 9AM Thu,"[0x52d7836c2b519b77:0x74c84187e38f42b, 0x52d78...",https://www.google.com/maps/place//data=!4m2!3...
4,Gray Brothers Dairy,"Gray Brothers Dairy, 408 N Main St, Stanley, N...",0x5320bcc09c8e6f15:0xc888ebee3ea483b6,None,48.324312,-102.390000,None,5.0,1,None,None,None,None,"[0x5320bcc63e8fe69d:0x4f22ad0dd39b1970, 0x5320...",https://www.google.com/maps/place//data=!4m2!3...

In [41]:
metadata['gmap_id'].nunique()

11937

In [43]:
newdf = metadata.merge(check, on='gmap_id')

In [45]:
print(newdf.shape)
print(newdf.columns)

(11987, 20)
Index(['name_x', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'category', 'avg_rating', 'num_of_reviews', 'price', 'hours', 'MISC',
       'state', 'relative_results', 'url', 'user_id', 'name_y', 'time',
       'rating', 'text'],
      dtype='object')

In [46]:
newdf.head()

,name_x,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url,user_id,name_y,time,rating,text
0,St Peter & Paul Church,"St Peter & Paul Church, 500 Main St, Karlsruhe...",0x52d94fbefa0e6353:0xf709e2d8674fe3a,None,48.093248,-100.618664,[Catholic church],4.9,7,None,None,{'Accessibility': ['Wheelchair accessible entr...,None,"[0x52d9384b75abac93:0x13526f8266cae6cf, 0x52d9...",https://www.google.com/maps/place//data=!4m2!3...,"[1.0884931397459742e+20, 1.1374804737693242e+2...","[أحمد آل إبراهيم, John OpenMinded, Juergen Wol...","[1600517759614, 1594757122443, 1574580027389, ...","[5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[I want to join Catholic Christ., Its Catholic..."
1,Northwest Martial Arts Academy,"Northwest Martial Arts Academy, 1430 Main Ave,...",0x52c8cbe775edec7d:0xb46e15ed33643070,None,46.875093,-96.802717,[Martial arts school],5.0,8,None,"[[Thursday, 7:30AM–8PM], [Friday, 7:30AM–8PM],...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 7:30AM,"[0x52c8ccbcb1785327:0x2d50311eabd7afc, 0x52cf3...",https://www.google.com/maps/place//data=!4m2!3...,"[1.0898058175328695e+20, 1.1691857878230558e+2...","[Lauren Swenson, Kayla Schmidt, Casyn r, Clint...","[1616035502642, 1610502595394, 1559792324852, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Northwest Martial Arts is amazing. Students ...
2,Thad's Amazing Magic - Fargo Birthday Party Magic,Thad's Amazing Magic - Fargo Birthday Party Ma...,0x52c8cd270f50bbbb:0x4ee4629598a8090e,None,46.812415,-96.856729,"[Magician, Children's party service]",5.0,58,None,"[[Thursday, Open 24 hours], [Friday, Open 24 h...",{'Amenities': ['Good for kids']},Open 24 hours,"[0x52c8c9613725e9ef:0xc628b86d8593e7e6, 0x52c8...",https://www.google.com/maps/place//data=!4m2!3...,"[1.1772908366123716e+20, 1.1254128413764223e+2...","[Nicole Hagman, Marcy Herrick, Jessi VanDyke, ...","[1624752031488, 1613917815807, 1615926223942, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[I cannot say enough amazing things about Farg...
3,Threefold,"Threefold, 212 W Main Ave, Bismarck, ND 58501",0x52d7836b7314da5d:0xc3cc63667b8c13a0,None,46.805707,-100.792990,"[Film production company, Video editing servic...",5.0,5,None,"[[Wednesday, 9AM–6PM], [Thursday, 9AM–6PM], [F...",None,Closed ⋅ Opens 9AM Thu,"[0x52d7836c2b519b77:0x74c84187e38f42b, 0x52d78...",https://www.google.com/maps/place//data=!4m2!3...,"[1.1596117273410172e+20, 1.08973695258937e+20,...","[Anthony Smith, Gustavo San Jose, Jason Mosser...","[1594248114960, 1543378323512, 1486527581269, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",[Threefold does high tier video work. If you n...
4,Gray Brothers Dairy,"Gray Brothers Dairy, 408 N Main St, Stanley, N...",0x5320bcc09c8e6f15:0xc888ebee3ea483b6,None,48.324312,-102.390000,None,5.0,1,None,None,None,None,"[0x5320bcc63e8fe69d:0x4f22ad0dd39b1970, 0x5320...",https://www.google.com/maps/place//data=!4m2!3...,"[1.0896313900617078e+20, 1.0896313900617078e+20]","[Peter Gilbertson, Peter Gilbertson]","[1520215144857, 1520215144857]","[5.0, 5.0]","[Love the dairy, Love the dairy]"

4.857142857142857